name: Mike Stacey
favicon: null
layout_spectrum: 0.98604
typography_spectrum: 0.6594725053291768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141414'
    - '#c0b9a8'
    - '#9e9788'
    - '#70685c'
    - '#322d27'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
